name: Test & Build
on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build tool
        run: |
          set -x && pushd cmd/terraform-provider-oauth >/dev/null && go build
